[package]
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
description = "A Rust client for the Holochain Conductor API"
edition = "2021"
homepage = "https://github.com/holochain/holochain-client-rust"
keywords = ["holochain", "client", "conductor-api"]
license = "CAL-1.0"
name = "holochain_client"
readme = "README.md"
repository = "https://github.com/holochain/holochain-client-rust"
resolver = "2"
version = "0.2.0"

[workspace]
members = ["fixture/zomes/foo", "utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
again = "0.1"
anyhow = "1.0"
ed25519-dalek = "1"
holo_hash = {version = "0.1.0-beta-rc.2", features = ["encoding"]}
holochain_conductor_api = "0.1.0-beta-rc.4"
holochain_serialized_bytes = "0.0.51"
holochain_types = "0.1.0-beta-rc.3"
holochain_websocket = "0.1.0-beta-rc.0"
holochain_zome_types = "0.1.0-beta-rc.3"
serde = "1"
url = "2.2"

[dev-dependencies]
arbitrary = "1.2"
holochain = {version = "0.1.0-beta-rc.4", features = ["test_utils"]}
rand = "0.7"
tokio = {version = "1.3", features = ["full"]}
utilities = {path = "utilities"}
