[package]
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
description = "A Rust client for the Holochain Conductor API"
edition = "2021"
homepage = "https://github.com/holochain/holochain-client-rust"
keywords = ["holochain", "client", "conductor-api"]
license = "CAL-1.0"
name = "holochain_client"
readme = "README.md"
repository = "https://github.com/holochain/holochain-client-rust"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
again = "0.1"
anyhow = "1.0"
holochain_conductor_api = "0.0.54"
holochain_types = "0.0.52"
holochain_websocket = "0.0.39"
serde = "1"
url = "2.2"

[dev-dependencies]
holochain = {version = "0.0.156", features = ["test_utils"]}
tokio = {version = "1.3", features = ["full"]}
