[package]
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
description = "A Rust client for the Holochain Conductor API"
edition = "2021"
homepage = "https://github.com/holochain/holochain-client-rust"
keywords = ["holochain", "client", "conductor-api"]
license = "MIT"
name = "holochain_client"
readme = "README.md"
repository = "https://github.com/holochain/holochain-client-rust"
resolver = "2"
version = "0.4.10"

[workspace]
members = ["fixture/zomes/foo"]

[workspace.dependencies]
holochain_zome_types = "0.2.7"

[dependencies]
again = "0.1"
anyhow = "1.0"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
event-emitter-rs = "0.1"
holo_hash = { version = "0.2.6", features = ["encoding"] }
holochain_conductor_api = "0.2.7"
holochain_serialized_bytes = "0.0.53"
holochain_state = "0.2.7"
holochain_types = "0.2.7"
holochain_websocket = "0.2.8-rc.0"
holochain_zome_types = { workspace = true }
serde = ">=1.0.0, <=1.0.166"
url = "2.2"
rand = "0.8"
async-trait = "0.1"
parking_lot = "0.12.1"
tokio = { version = "1.36", features = ["rt"] }

[dev-dependencies]
arbitrary = "1.2"
holochain = { version = "0.2.8-rc.0", features = ["test_utils"] }
