[package]
authors = ["Guillem Cordoba <guillem.cordoba@gmail.com>"]
description = "A Rust client for the Holochain Conductor API"
edition = "2021"
homepage = "https://github.com/holochain/holochain-client-rust"
keywords = ["holochain", "client", "conductor-api"]
license = "CAL-1.0"
name = "holochain_client"
readme = "README.md"
repository = "https://github.com/holochain/holochain-client-rust"
resolver = "2"
version = "0.4.4"

[workspace]
members = ["fixture/zomes/foo", "utilities"]

[workspace.dependencies]
holochain_zome_types = "0.2.3-beta-rc.0"

[dependencies]
again = "0.1"
anyhow = "1.0"
ed25519-dalek = "1"
holo_hash = {version = "0.2.3-beta-rc.0", features = ["encoding"]}
holochain_conductor_api = "0.2.3-beta-rc.1"
holochain_serialized_bytes = "=0.0.53"
holochain_types = "0.2.3-beta-rc.0"
holochain_websocket = "0.2.2"
holochain_zome_types = { workspace = true }
serde = ">=1.0.0, <=1.0.166"
url = "2.2"

[dev-dependencies]
arbitrary = "1.2"
holochain = {version = "0.2.3-beta-rc.1", features = ["test_utils"]}
rand = "0.7"
tokio = {version = "1.3", features = ["full"]}
utilities = {path = "utilities"}
